[ludens_project]
version_major = 0
version_minor = 0
version_patch = 0
name = "first game"
assets = "./assets.toml"
scenes = ["./scenes/main.toml"]

[settings.startup]
window_width = 1080
window_height = 540
window_name = "foo"
default_scene_path = "scenes/main.toml"

[settings.screen_layer]
layers = [ {name='default', id=1}, {name='fg', id=2} ]