[ludens_assets]
version_major = 0
version_minor = 0
version_patch = 0
auid_counter = 101

[[TextureCube]]
uri = "../../skybox/blue_photo_studio/cubemap.lda"
auid = 10
name = "default_cubemap"

[[Font]]
uri = "../assets/font/Inter_24pt-Regular.lda"
auid = 3
name = "default_font"

[[Mesh]]
uri = "../assets/gltf/backpack/backpack.lda"
auid = 1
name = "backpack"

[[Mesh]]
uri = "../assets/gltf/platform/platform00.lda"
auid = 2
name = "platform00"

[[Mesh]]
uri = "../assets/gltf/cerberus/cerberus.lda"
auid = 4
name = "cerberus"

[[Mesh]]
uri = "../assets/gltf/DamagedHelmet/glTF/DamagedHelmet.lda"
auid = 5
name = "DamagedHelmet"

[[Mesh]]
uri = "../assets/gltf/oiiaioooooiai_cat/cat.lda"
auid = 7
name = "cat"

[[Mesh]]
uri = "../assets/gltf/very_low_poly_cowboy_hat/hat.lda"
auid = 8
name = "hat"

[[LuaScript]]
uri = "../assets/lua/script.lda"
auid = 300
name = "script"

[[LuaScript]]
uri = "../assets/lua/audioPlayer.lda"
auid = 301
name = "audioPlayer"

[[LuaScript]]
uri = '../assets/lua/sprite.lda'
auid = 302
name = "sprite"

[[AudioClip]]
uri = "../assets/audio/forest.lda"
auid = 100
name = "forest"

[[AudioClip]]
uri = "../assets/audio/oiiai.lda"
auid = 101
name = "oiiai"

[[Texture2D]]
uri = "../../../Texture/lobster.lda"
auid = 200
name = "lobster"

[[Texture2D]]
uri = "../../../Texture/duck.lda"
auid = 201
name = "duck"