[ludens_scene]
version_major = 0
version_minor = 0
version_patch = 0

[[component]]
perspective = {fov = 45.0, nearClip = 0.1, farClip = 100.0}
isPerspective = true
type = "Camera"
name = "MainCamera"
id = 8
transform = {position = [-3.61957, -1.20363, -18.0253], rotation = [0.0, 0.0, 0.0], scale = [1.0, 1.0, 1.0]}
isMainCamera = true

[[component]]
id = 6
texture_2d_id = 200
name = "Sprite1"
type = "Sprite2D"
local = { x = 0, y = 0, w = 100, h = 100 }
transform = { position = [10, 10], rotation = 0.0, scale = [1.0, 1.0]}
z_depth = 2

[[component]]
id = 7
texture_2d_id = 201
name = "Sprite2"
type = "Sprite2D"
local = { x = 0, y = 0, w = 100, h = 100 }
transform = { position = [60, 10], rotation = 0.0, scale = [1.0, 1.0]}
z_depth = 1

[[component]]
id = 9
texture_2d_id = 201
name = "Sprite3"
type = "Sprite2D"
local = { x = 0, y = 0, w = 100, h = 100 }
transform = { position = [110, 10], rotation = 0.0, scale = [1.0, 1.0]}
z_depth = 0
