[ludens_scene]
version_major = 0
version_minor = 0
version_patch = 0

[[component]]
script = 6
cuid = 1
name = "Backpack"
type = "Mesh"
transform = { position = [0.0, 0.0, 0.0], rotation = [0.0, 0.0, 0.0], scale = [0.01, 0.01, 0.01] }
auid = 1

[[component]]
cuid = 2
name = "Platform"
type = "Mesh"
transform = { position = [0.0, -6.0, 0.0], rotation = [0.0, 0.0, 0.0], scale = [1.0, 1.0, 1.0] }
auid = 2

[[component]]
cuid = 3
name = "Cerberus"
type = "Mesh"
transform = { position = [3.0, 0.0, 0.0], rotation = [0.0, 0.0, 0.0], scale = [0.02, 0.02, 0.02] }
auid = 4

[[component]]
cuid = 4
script = 6
name = "DamagedHelmet"
type = "Mesh"
transform = { position = [-3.0, 0.0, 0.0], rotation = [0.0, 0.0, 0.0], scale = [5.0, 1.0, 5.0] }
auid = 5

[[component]]
cuid = 5
name = "Cat"
type = "Mesh"
transform = { position = [-5.0, -3.0, -2.0], rotation = [0.0, 0.0, 0.0], scale = [5.0, 5.0, 5.0] }
auid = 7

[[component]]
cuid = 6
name = "Hat"
type = "Mesh"
transform = { position = [0.0, 0.329, 0.083], rotation = [0.0, 0.0, 0.0], scale = [0.01, 0.01, 0.01] }
auid = 8

[[component]]
cuid = 7
script = 9
name = "Audio"
type = "AudioSource"
auid = 100

[[component]]
cuid = 8
name = "MainCamera"
type = "Camera"
transform = { position = [0.0, 3.0, -10.0], rotation = [0.0, 0.0, 0.0], scale = [1.0, 1.0, 1.0] }
isPerspective = true
isMainCamera = true
perspective = { fov = 45.0, nearClip = 0.1, farClip = 100.0 }

[hierarchy]
"2" = [1, 4]
"5" = [6]
