[hierarchy]
2 = [1, 4]
5 = [6, 7]

[[component]]
type = "Mesh"
auid = 1
name = "Backpack"
cuid = 1
transform = {position = [13.4756, 0.0, -10.9651], rotation = [0.0, 0.0, 0.0], scale = [0.01, 0.01, 0.01]}

[[component]]
type = "Mesh"
auid = 5
name = "DamagedHelmet"
cuid = 4
transform = {position = [2.55821, 5.42545, 0.0], rotation = [0.0, 0.0, 0.0], scale = [1.74343, 1.0, 1.71553]}

[[component]]
type = "Mesh"
auid = 2
name = "Platform"
cuid = 2
transform = {position = [-4.38353, -6.0, -6.03717], rotation = [0.0, 0.0, 0.0], scale = [1.0, 1.0, 1.0]}

[[component]]
type = "Mesh"
auid = 4
name = "Cerberus"
cuid = 3
transform = {position = [3.0, 0.0, 0.0], rotation = [0.0, 0.0, 0.0], scale = [0.02, 0.02, 0.02]}

[[component]]
type = "Mesh"
auid = 8
name = "Hat"
cuid = 6
transform = {position = [0.0, 0.329, 0.083], rotation = [0.0, 0.0, 0.0], scale = [0.01, 0.01, 0.01]}

[[component]]
type = "Mesh"
auid = 7
name = "Cat"
cuid = 5
transform = {position = [-7.81519, -3.75509, -2.0], rotation = [0.0, 0.0, 0.0], scale = [5.0, 5.0, 5.0]}
script = 300

[[component]]
type = "AudioSource"
auid = 100
name = "Audio"
cuid = 7
pan = 0.5
volumeLinear = 1.0

[[component]]
perspective = {fov = 45.0, nearClip = 0.1, farClip = 100.0}
isPerspective = true
type = "Camera"
name = "MainCamera"
cuid = 8
transform = {position = [-3.61957, -1.20363, -18.0253], rotation = [0.0, 0.0, 0.0], scale = [1.0, 1.0, 1.0]}
isMainCamera = true

[ludensScene]
versionMajor = 0
versionMinor = 0
versionPatch = 0

